let first = "Laurence";
let last = "Svekis";
let fullName = first + " " + last;
console.log(fullName);
console.log(first.length);
console.log(first[3]);
let val = first.toUpperCase();
console.log(val.toLowerCase());
fullName = "More stuff " + fullName + " even more content";
let start = fullName.indexOf(last);
let len = last.length;
let end = start + len;
let firstSlice = fullName.slice(7);
console.log(firstSlice);
let secondSlice = fullName.slice(7, 17);
let findWord = fullName.slice(start, end);
console.log(findWord);
let val1 = fullName.substring(start, end);
console.log(val1);
let val2 = fullName.substr(start, len);
console.log(val2);